name: .NET with K6

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        options: --privileged
        ports:
          - 5000:80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./out

      - name: Start application
        run: dotnet run --project RateLimitersDemo --urls "http://localhost:5000" &
        env:
          ASPNETCORE_ENVIRONMENT: Production

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          path: LoadTests/script.js
          cloud-run-locally: false
          parallel: false
          fail-fast: false
