name: .NET with

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        options: --privileged
        ports:
          - 5000:80

    env:
      BASE_URL: http://localhost:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./out

      - name: Build Docker image
        run: docker build -t demo -f Dockerfile .

      - name: Run Docker container
        run: docker run -d -p 5000:80 demoapp

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run K6 Load Test
        run: k6 run -e BASE_URL=$BASE_URL ./LoadTests/script.js
